# Generated by Django 4.2 on 2023-05-03 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
