# Generated by Django 4.2 on 2023-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_item_added_date_alter_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='items_pics'),
        ),
    ]
