# Generated by Django 4.2 on 2023-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_alter_customer_name_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
